# Odoo yaml template for travis-ci
# __version__=0.2.1.54

language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

virtualenv:
  system_site_packages: true

git:
  submodules: false

addons:
  apt:
    sources:
      - pov-wkhtmltopdf
#   Search your sources alias here:
#     https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - python-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - curl
      - nodejs
      - npm
      - python-ldap
      - python-psycopg2
      - python-simplejson
      - expect-dev
      - python-setuptools
#   Search your packages here:
#     https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

before_install:
  - export TRAVIS_DEBUG_MODE="1"
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --depth=1
  - mv ${HOME}/tools/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

install:
  - travis_install_env
  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery
  # - export INCLUDE=$(getaddons.py -m ${HOME}/build/${ODOO_REPO}/odoo/addons ${HOME}/build/${ODOO_REPO}/addons)

env:
  global:
  - VERSION="7.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  # - LINT_CHECK="1" LINT_CHECK_LEVEL="MINIMAL"
  - TESTS="0" ODOO_REPO="odoo/odoo"
  - TESTS="0" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="zeroincombenze/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="zeroincombenze/OCB" UNIT_TEST="1"

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success

