language: python

python:
  - "2.7"

sudo: false
cache: pip

git:
  submodules: false

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="7.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0" UNIT_TEST="1"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: "XzZzWhiVWXHI+tmcdYH0rPjietxvr1nUXuCRiqnDY3fM0lq6RmtwOlpDDwYEiX+9fHAE8mDttlJ7H4J/YZ+0ugwZxeM10yuT7FwkJY9kPvBe6T59P9aD9R6mSC/da4JGVd+Th5QXDBuBGRBVdY/qBT2lagHuSzBZdKwvMMsaBtA="

  matrix:
  - LINT_CHECK="1"
  # - TRANSIFEX="1"
  - TESTS="0" ODOO_REPO="odoo/odoo"
  - TESTS="0" ODOO_REPO="OCA/OCB"
  - UNIT_TEST="1" EXCLUDE=record_archiver

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --depth=1
  - mv ${HOME}/tools/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

install:
  # - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  # - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  # - pip install python-ldap raven raven_sanitize_openerp
  - pip install python-ldap 
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
